#include "pnmtologo.h"
#include "util.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *USAGE = "USAGE: genstaticlogo static_struct_name file.ppm <file.c>";

static inline void write_logo_header(FILE *out, const char *struct_name)
{
    fputs("/*\n", out);
    fputs(" *  DO NOT EDIT THIS FILE!\n", out);
    fputs(" *\n", out);
    fprintf(out, " *  It was automatically generated from image file\n");
    fputs(" *\n", out);
    fprintf(out, " * Static dietsplash image\n");
    fputs(" */\n\n", out);
    fputs("#include \"pnmtologo.h\"\n\n", out);
    fputs("#ifndef __DIETSPLASH_STATICLOGO_C\n" \
          "#define __DIETSPLASH_STATICLOGO_C\n\n", out);
    fprintf(out, "static struct image %s = {\n", struct_name);
}

static inline void write_logo_properties(FILE *out, struct image *logo)
{
    fprintf(out, "    .width = %d,\n", logo->width);
    fprintf(out, "    .height = %d,\n", logo->height);
}

static inline void write_logo_data(FILE *out, struct image *logo)
{
    long i;
    fputs("    .pixels = {\n", out);
    for (i = 0; i < logo->width * logo->height; i++) {
        fprintf(out, "        { 0x%02x, 0x%02x, 0x%02x },\n",
                logo->pixels[i].red,
                logo->pixels[i].green,
                logo->pixels[i].blue);
    }
    fputs("    }\n", out);
}

static inline void write_logo_footer(FILE *out)
{
    fputs("};\n\n#endif", out);
}

int main(int argc, char *argv[])
{
    struct image *logo;
    const char *filename_out = NULL;
    const char *filename_in;
    const char *static_struct_name;
    static FILE *fp_out;

    if (argc < 3 || argc > 4)
        die("%s", USAGE);

    static_struct_name = argv[1];
    filename_in = argv[2];
    if (argc == 4)
        filename_out = argv[3];

    /* open logo file */
    if (filename_out && strcmp(filename_out, "-")) {
	fp_out = fopen(filename_out, "w");
	if (!fp_out)
	    die("Cannot create file %s: %s\n", filename_out, strerror(errno));
    } else {
	fp_out = stdout;
    }

    logo = ds_read_image(filename_in);
    write_logo_header(fp_out, static_struct_name);
    write_logo_properties(fp_out, logo);
    write_logo_data(fp_out, logo);
    write_logo_footer(fp_out);

    fclose(fp_out);
    free(logo);

    return 0;
}
